FROM debian:stable-slim

ENV CWD=/opt/app HOME=/opt/app TERM=xterm

RUN apt-get update && apt-get install -y bash curl inotify-tools git build-essential libtinfo5

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn
WORKDIR /opt/app
EXPOSE 5000/tcp
CMD ["bash"]